### ISSUE TITLE
[WebSocket Server] We are not managing clients connected to the server. Also the WebServer stops serving files when

### ISSUE THREAD

**Issue by ccostel** [faraday-motion/pacer#2]
Replication: 
---
Connect 5 clients to the WebSocket server: ws://10.10.100.254:81 
Try to access 10.10.100.254/index.html
ESP8266 stalls.

Some ideas: 
--
Have a heartbeat check with all clients. If not response is received back from the client remove the client.

Library that is used: https://github.com/Links2004/arduinoWebSockets

**Comment by cerdemir** [comment]
Problem reproduced. ESP backs to normal state after clients disconnected.
