### ISSUE TITLE
[Refactor] Create an abstract class for wired/wireless devices connected to pacer.

### ISSUE THREAD

**Issue by ccostel** [faraday-motion/pacer#6]
Early on there was an attempt to abstract devices that are connecting to Pacer. However it turned out to be challenging as different devices have different specifications. As of now the connecting devices are mainly controllers and are wireless. 

The classes can be found here: https://github.com/faraday-motion/pacer/tree/master/src/components/Device

You can see how currently we are using the abstract device to register controller here: 

**components/Connection/ConnectionManager.cpp**
Each connection type is handling the registration of a `pendingDevice` that should be abstracted. 
```
void ConnectionManager::handleClientConnections()
{
  if (handleClientInterval->check() == 1)
  {
    this->handleWifiConnections();
    this->handleRadioConnections();
    this->healthCheckWebSocketConnections();
  }
}
```

**components/Connection/Wifi/Wifi.cpp**
`Wifi.cpp` is using the `components/Device/WifiDevice.h` for its pendingDevice
```
/** Checks if wifi is instantiated and checks for new clinets wanting to connect */
void ConnectionManager::handleWifiConnections()
{
  if (this->wifi != nullptr)
  {
    if (this->wifi->handleClientConnections() == true) {
      // Log::Logger()->write(Log::Level::DEBUG, "Wifi Detected New Pending Device");
      // TODO:: We have an issue the pending devices are being overwritten here by handleRadioConnections()
      this->pendingDevice = this->wifi->pendingDevice;
    }
  }
}  
```

**components/Connection/Radio/RadioHandshake.cpp**
`Radiohandshake.cpp` is using the `components/Device/AbstractDevice.h`
```
/** Checks if radio is instantiated and checks for new clinets wanting to connect */
void ConnectionManager::handleRadioConnections()
{
  if (this->radio != nullptr)
  {
    this->radioHandshake->handleHandshake();
    if (this->radioHandshake->pendingDevice.pending == true)
    {
      Log::Logger()->write(Log::Level::DEBUG, "Flagging a pending radio device.");
      // Copy the pending Device so that FMV can work with it.
      bool registerd = this->controllerManager->registerController(this->radioHandshake->pendingDevice);
      if (registerd)
        this->radioHandshake->pendingDevice.isRegisterd = true; // Flag registration succeeded.
    }
  }

}
```

**components/Connection/WebSocket/WebsocketCommunication.cpp**

WebSocket clients are a bit different as they are auto connected and by pass the pendingDevice layer. This should be subject to a discussion.

Now WebSocket clients can register themselves as controllers through the `Console.cpp`

**Comment by sunepedersen** [comment]
Fixed with the upcoming esp32 branch
