### ISSUE TITLE
[VESC] Optimize the way we communicate with VESC. The callbacks are not an optimal solution. There's potential garbage in the serial print because of that.

### ISSUE THREAD

**Issue by ccostel** [faraday-motion/pacer#7]
We are using the following VESC library for being able to communicate with the VESC. 
https://github.com/faraday-motion/bldc_uart_comm_stm32f4_discovery
Read more about what I used to implement this here: 
http://vedder.se/2015/10/communicating-with-the-vesc-using-uart/

Because that library is written in C and requires callback functions and we cannot set class methods as such callbacks I had to do a workaround that is all but optimal. 

You will see that in `src/FMV.cpp` we have a while loop that checks if there's serial data and triggers the processing of the VESC UART bytes. 
```
// Read Data from VESC  // TODO:: This should be moved somewhere else.
    while (Serial.available() > 0) this->controllerManager->motorController->processUartByte(Serial.read());
```
I have two assumptions here:
1. This produces garbage on the serial monitor
2. This could be process intensive for the ESP.

Here' where the mess really begins: 
===
Step 1
--
`components/MotorController/MotorController.cpp::processUartByte(usnigned char b)`
is calling `bldc_interface_uart_process_byte(b)` from the `bldc_uart_comm_stm32f4_discovery` library 

Step 2
---
`bldc_interface_uart_process_byte(b)` triggers the plain callback in `components/MotorController/VescUtility.h` called `void printValues(mc_values *val)`

Step 3 
---  
`void printValues(mc_values *val)` stores the values in a singleton class called `VescParams.h`. 

Step 4 
--- 
We access the singleton `VescParams.h` to read those values in different parts of the application.

Note:
--
For each of the commands that we want to send to the VESC we have to register a different callback. 

This is a huge issue and needs to be solved. 

Here are some potential solutions: 
1. We could process the packets on our own based on the library source code. 
https://github.com/faraday-motion/bldc_uart_comm_stm32f4_discovery/blob/master/bldc_interface.c#L130

2. We can find a better way to register the callbacks. 

3. Currently I can't think of a third one. 

Note 2
---
Keep in mind that we need to also abstract the VESC from the `MotorController.h` class. 
See more here:  https://github.com/faraday-motion/pacer/issues/8

**Comment by sunepedersen** [comment]
Fixed with the upcoming esp32 branch
