### ISSUE TITLE
[Motor Controller] Create an abstraction layer for MotorControllers. Now we only support VESC but want to be able to use other motor controllers.

### ISSUE THREAD

**Issue by ccostel** [faraday-motion/pacer#8]
Now we are only supporting the VESC motor controller and we are using UART to communicate to it. 

As we want Pacer to become more universal we need to have the ability to add new types of motor controllers. 

The challenge is to have an abstraction layer for the motor controller.

**Comment by cerdemir** [comment]
How many motor controllers should pacer manage at the same time?

**Comment by ccostel** [comment]
@cerdemir For now the maximum amount of VESCs we are using is 4. That is used for a 4 wheel drive electric skateboard. 

The VESCs are connected through  CAN and we're basically forwarding the commands. 

I think initially we can aim for a maxim of 4 but in the future I could see scenarios of 6-8 wheel driven vehicles. :)

**Comment by cerdemir** [comment]
Sorry @ccostel  
I want to ask how many types of motor controller should pacer manage at the same configuration?
And do you have any plan about how to steering pacer?

- Differential steering we  need to group motors(or motor controllers). 
- Basic steering we need to figure out how to handle it.

**Comment by sunepedersen** [comment]
@cerdemir everything we currently are working on is maximum 4 wheels. This might change in the future but we do not know yet. I suggest that we configure the "wheels" with something like the following properties, isElectric, canSteer, inverse (steer and power/brake), power (%), brake (%), RPM etc and then we configure a controller type for each. 

For now we are focusing on VESC that supports CAN bus where we are using one entry point UART to control all VESC's on the system. However, alternative controllers will be controlled by either UART (with the hardware limitations for number of UART's), PWM or Analog output.

I suggest we focus on VESC and PWM motor control for now as this is the most adopted and compliant with our hardware.

Steering can be set up per wheel, or per group of wheels. Same with power/brake (also think of advanced features like antispin/tourque vectoring that can affect one wheel individually needs to be able to be supported in the future).

**Comment by sunepedersen** [comment]
Fixed with the upcoming esp32 branch
