### ISSUE TITLE
[Discussion] [Console] What is the role of the Console.h. How can we have an abstract layer for interacting with Pacer via different communication protocols.

### ISSUE THREAD

**Issue by ccostel** [faraday-motion/pacer#9]
Uhg.. 

I love and hate this Console component. We are able to interact with the Pacer Vehicle very easily which is very good. At the same time the console seems to have too much power over the Pacer vehicle. More to that the Console got quite messy in the code. 

Let's try and define what should be the role of the Console be and how can we secure it.

**Comment by cerdemir** [comment]
**Messaging**
Every command in console can be called from different sources(communication interface) and and these sources can have different message patterns(for ex: binary in bluetooth, json in WS ). In this reason every command should correspond interface agnostic messages. 

This agnostic messages can be translate at the end of pipeline before going outside of pacer. Internal messaging always walks with message format.

We need `MessageTranslators` for every single interface.

**Commands**

My suggestion is handle all command as a transaction (one transaction one derived class).  A transaction has two duties. Running transaction and provide a message which will translate to proper pattern later. For this architecture we should figure out how to supply dependencies to transactions and how to build a transaction factory.

**Comment by sunepedersen** [comment]
Fixed with the upcoming esp32 branch
